name: "Temzit MQTT Bridge"
version: "0.1.1"
slug: "temzit_mqtt_bridge"
description: "Local TCP to MQTT bridge for Temzit heat pumps"
url: "https://github.com/daemon707/temzit-addon/tree/main/temzit_mqtt_bridge"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
host_network: true
map:
  - config:rw
options:
  temzit_host: ""
  temzit_port: 333
  temzit_timeout: 5
  temzit_sync_interval: 30
  temzit_cfg_interval: 300
  temzit_retry_delay: 3
  mqtt_host: ""
  mqtt_port: 
  mqtt_user: ""
  mqtt_pass: ""
  mqtt_prefix: "temzit"
  mqtt_discovery_prefix: "homeassistant"
  mqtt_client_id: "temzit-bridge"
schema:
  temzit_host: "str"
  temzit_port: "int"
  temzit_timeout: "float"
  temzit_sync_interval: "int"
  temzit_cfg_interval: "int"
  temzit_retry_delay: "float"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_user: "str"
  mqtt_pass: "str"
  mqtt_prefix: "str"
  mqtt_discovery_prefix: "str"
  mqtt_client_id: "str"
